// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Solve = __t.object("Solve", {
  id: __t.u64(),
  owner: __t.identity(),
  event: __t.string(),
  time: __t.u32(),
  solvedAt: __t.timestamp(),
  penalty: __t.string(),
  scramble: __t.option(__t.string()),
  comment: __t.option(__t.string()),
});
export type Solve = __Infer<typeof Solve>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

