// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import AddSolveReducer from "../add_solve_reducer";
import DeleteSolveReducer from "../delete_solve_reducer";
import SayHelloReducer from "../say_hello_reducer";
import UpdatePenaltyReducer from "../update_penalty_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type AddSolveParams = __Infer<typeof AddSolveReducer>;
export type DeleteSolveParams = __Infer<typeof DeleteSolveReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type UpdatePenaltyParams = __Infer<typeof UpdatePenaltyReducer>;

